name: CI/CD for Dockerized flask App

on: 
  push: 
    branch: [ main ]
  pull_request:
    branch: [main ]

jobs:
  build-and-test: 
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: action/checkout@v3

   - name: Set up Python
     uses: action/setup-python@v4
     with:  
       python-version:  '3.9'

   - name: Install dependencies
     run: 
       python -m pip install --upgrade pip
       pip install flask
       pip install pytest

   - name: Run test
     run: |
       pytest

  build-and-publish:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: check code
      uses: actions/checkout@v3

    - name: set up Docker Builddx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        pasword:  ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and pussh Docker image
      uses: docker/build-push-action@v4
      with: 
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flask-app.latest

    - name: Image digest
      run: echo ${{ steps.build-and-publish.output.digest }}

